# 配置应用，默认可以不更改
[app]
name = "MySQL2CSV"
thread_num = 12                         # 线程数
batch_size = 10000                      # 批量大小
output_dir = "./output/"                # 输出文件目录
output_file_name = "output_file_name"   # 输出文件名
save_tmp_file = "true"                 # 是否保存临时文件

# 配置mysql
[mysql]
host = "127.0.0.1"          # 主机
port = "3306"                   # 端口
database = "db_test"            # 数据库
username = "root"               # 用户名
password = "root" # 密码
table = "users"                 # 表名
columns = "name,age,email"      # 列名